version: "3.7"
services:
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USERNAME: julietnu
      POSTGRES_DB: julietnu
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5430"
  web:
    image: ota
    depends_on:
      - db
    ports:
      - "4000:4000"
